In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

from pathlib import Path

pd.set_option("display.max_columns", None)
pd.set_option("display.max_rows", 100)

In [3]:
BASE_DIR = Path("../")

RAW_DATA_DIR = BASE_DIR / "data" / "raw"
PROCESSED_DATA_DIR = BASE_DIR / "data" / "processed"

old_data_path = RAW_DATA_DIR / "sensor.csv"

In [4]:
df_old = pd.read_csv(old_data_path)

print("Old Dataset:", df_old.shape)

Old Dataset: (220320, 55)

In [5]:
df_old.head()

,Unnamed: 0,timestamp,sensor_00,sensor_01,sensor_02,sensor_03,sensor_04,sensor_05,sensor_06,sensor_07,sensor_08,sensor_09,sensor_10,sensor_11,sensor_12,sensor_13,sensor_14,sensor_15,sensor_16,sensor_17,sensor_18,sensor_19,sensor_20,sensor_21,sensor_22,sensor_23,sensor_24,sensor_25,sensor_26,sensor_27,sensor_28,sensor_29,sensor_30,sensor_31,sensor_32,sensor_33,sensor_34,sensor_35,sensor_36,sensor_37,sensor_38,sensor_39,sensor_40,sensor_41,sensor_42,sensor_43,sensor_44,sensor_45,sensor_46,sensor_47,sensor_48,sensor_49,sensor_50,sensor_51,machine_status
0,0,2018-04-01 00:00:00,2.465394,47.09201,53.2118,46.310760,634.3750,76.45975,13.41146,16.13136,15.56713,15.05353,37.22740,47.52422,31.11716,1.681353,419.5747,NaN,461.8781,466.3284,2.565284,665.3993,398.9862,880.0001,498.8926,975.9409,627.6740,741.7151,848.0708,429.0377,785.1935,684.9443,594.4445,682.8125,680.4416,433.7037,171.9375,341.9039,195.0655,90.32386,40.36458,31.51042,70.57291,30.98958,31.770832,41.92708,39.641200,65.68287,50.92593,38.194440,157.9861,67.70834,243.0556,201.3889,NORMAL
1,1,2018-04-01 00:01:00,2.465394,47.09201,53.2118,46.310760,634.3750,76.45975,13.41146,16.13136,15.56713,15.05353,37.22740,47.52422,31.11716,1.681353,419.5747,NaN,461.8781,466.3284,2.565284,665.3993,398.9862,880.0001,498.8926,975.9409,627.6740,741.7151,848.0708,429.0377,785.1935,684.9443,594.4445,682.8125,680.4416,433.7037,171.9375,341.9039,195.0655,90.32386,40.36458,31.51042,70.57291,30.98958,31.770832,41.92708,39.641200,65.68287,50.92593,38.194440,157.9861,67.70834,243.0556,201.3889,NORMAL
2,2,2018-04-01 00:02:00,2.444734,47.35243,53.2118,46.397570,638.8889,73.54598,13.32465,16.03733,15.61777,15.01013,37.86777,48.17723,32.08894,1.708474,420.8480,NaN,462.7798,459.6364,2.500062,666.2234,399.9418,880.4237,501.3617,982.7342,631.1326,740.8031,849.8997,454.2390,778.5734,715.6266,661.5740,721.8750,694.7721,441.2635,169.9820,343.1955,200.9694,93.90508,41.40625,31.25000,69.53125,30.46875,31.770830,41.66666,39.351852,65.39352,51.21528,38.194443,155.9606,67.12963,241.3194,203.7037,NORMAL
3,3,2018-04-01 00:03:00,2.460474,47.09201,53.1684,46.397568,628.1250,76.98898,13.31742,16.24711,15.69734,15.08247,38.57977,48.65607,31.67221,1.579427,420.7494,NaN,462.8980,460.8858,2.509521,666.0114,399.1046,878.8917,499.0430,977.7520,625.4076,739.2722,847.7579,474.8731,779.5091,690.4011,686.1111,754.6875,683.3831,446.2493,166.4987,343.9586,193.1689,101.04060,41.92708,31.51042,72.13541,30.46875,31.510420,40.88541,39.062500,64.81481,51.21528,38.194440,155.9606,66.84028,240.4514,203.1250,NORMAL
4,4,2018-04-01 00:04:00,2.445718,47.13541,53.2118,46.397568,636.4583,76.58897,13.35359,16.21094,15.69734,15.08247,39.48939,49.06298,31.95202,1.683831,419.8926,NaN,461.4906,468.2206,2.604785,663.2111,400.5426,882.5874,498.5383,979.5755,627.1830,737.6033,846.9182,408.8159,785.2307,704.6937,631.4814,766.1458,702.4431,433.9081,164.7498,339.9630,193.8770,101.70380,42.70833,31.51042,76.82291,30.98958,31.510420,41.40625,38.773150,65.10416,51.79398,38.773150,158.2755,66.55093,242.1875,201.3889,NORMAL

In [6]:
df_old.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 220320 entries, 0 to 220319
Data columns (total 55 columns):
 #   Column          Non-Null Count   Dtype
---  ------          --------------   -----
 0   Unnamed: 0      220320 non-null  int64
 1   timestamp       220320 non-null  object
 2   sensor_00       210112 non-null  float64
 3   sensor_01       219951 non-null  float64
 4   sensor_02       220301 non-null  float64
 5   sensor_03       220301 non-null  float64
 6   sensor_04       220301 non-null  float64
 7   sensor_05       220301 non-null  float64
 8   sensor_06       215522 non-null  float64
 9   sensor_07       214869 non-null  float64
 10  sensor_08       215213 non-null  float64
 11  sensor_09       215725 non-null  float64
 12  sensor_10       220301 non-null  float64
 13  sensor_11       220301 non-null  float64
 14  sensor_12       220301 non-null  float64
 15  sensor_13       220301 non-null  float64
 16  sensor_14       220299 non-null  float64
 17  sensor_15       0 non-null       float64
 18  sensor_16       220289 non-null  float64
 19  sensor_17       220274 non-null  float64
 20  sensor_18       220274 non-null  float64
 21  sensor_19       220304 non-null  float64
 22  sensor_20       220304 non-null  float64
 23  sensor_21       220304 non-null  float64
 24  sensor_22       220279 non-null  float64
 25  sensor_23       220304 non-null  float64
 26  sensor_24       220304 non-null  float64
 27  sensor_25       220284 non-null  float64
 28  sensor_26       220300 non-null  float64
 29  sensor_27       220304 non-null  float64
 30  sensor_28       220304 non-null  float64
 31  sensor_29       220248 non-null  float64
 32  sensor_30       220059 non-null  float64
 33  sensor_31       220304 non-null  float64
 34  sensor_32       220252 non-null  float64
 35  sensor_33       220304 non-null  float64
 36  sensor_34       220304 non-null  float64
 37  sensor_35       220304 non-null  float64
 38  sensor_36       220304 non-null  float64
 39  sensor_37       220304 non-null  float64
 40  sensor_38       220293 non-null  float64
 41  sensor_39       220293 non-null  float64
 42  sensor_40       220293 non-null  float64
 43  sensor_41       220293 non-null  float64
 44  sensor_42       220293 non-null  float64
 45  sensor_43       220293 non-null  float64
 46  sensor_44       220293 non-null  float64
 47  sensor_45       220293 non-null  float64
 48  sensor_46       220293 non-null  float64
 49  sensor_47       220293 non-null  float64
 50  sensor_48       220293 non-null  float64
 51  sensor_49       220293 non-null  float64
 52  sensor_50       143303 non-null  float64
 53  sensor_51       204937 non-null  float64
 54  machine_status  220320 non-null  object
dtypes: float64(52), int64(1), object(2)
memory usage: 92.5+ MB

In [8]:
df_old.describe(include="all").T

,count,unique,top,freq,mean,std,min,25%,50%,75%,max
Unnamed: 0,220320.0,NaN,NaN,NaN,110159.5,63601.049991,0.0,55079.75,110159.5,165239.25,220319.0
timestamp,220320,220320,2018-04-01 00:00:00,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN
sensor_00,210112.0,NaN,NaN,NaN,2.372221,0.412227,0.0,2.438831,2.456539,2.499826,2.549016
sensor_01,219951.0,NaN,NaN,NaN,47.591611,3.296666,0.0,46.31076,48.133678,49.47916,56.72743
sensor_02,220301.0,NaN,NaN,NaN,50.867392,3.66682,33.15972,50.39062,51.6493,52.77777,56.03299
sensor_03,220301.0,NaN,NaN,NaN,43.752481,2.418887,31.64062,42.838539,44.227428,45.3125,48.22049
sensor_04,220301.0,NaN,NaN,NaN,590.673936,144.023912,2.798032,626.6204,632.638916,637.615723,800.0
sensor_05,220301.0,NaN,NaN,NaN,73.396414,17.298247,0.0,69.97626,75.57679,80.91215,99.99988
sensor_06,215522.0,NaN,NaN,NaN,13.501537,2.163736,0.014468,13.34635,13.64294,14.53993,22.25116
sensor_07,214869.0,NaN,NaN,NaN,15.843152,2.201155,0.0,15.90712,16.16753,16.42795,23.59664
sensor_08,215213.0,NaN,NaN,NaN,15.200721,2.03739,0.028935,15.18374,15.49479,15.69734,24.34896
sensor_09,215725.0,NaN,NaN,NaN,14.79921,2.091963,0.0,15.05353,15.08247,15.11863,25.0
sensor_10,220301.0,NaN,NaN,NaN,41.470339,12.093519,0.0,40.70526,44.29134,47.46376,76.10686
sensor_11,220301.0,NaN,NaN,NaN,41.918319,13.056425,0.0,38.85642,45.36314,49.65654,60.0
sensor_12,220301.0,NaN,NaN,NaN,29.136975,10.113935,0.0,28.68681,32.51583,34.93973,45.0
sensor_13,220301.0,NaN,NaN,NaN,7.078858,6.901755,0.0,1.538516,2.929809,12.85952,31.18755
sensor_14,220299.0,NaN,NaN,NaN,376.860041,113.206382,32.40955,418.10325,420.1062,420.9971,500.0
sensor_15,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
sensor_16,220289.0,NaN,NaN,NaN,416.472892,126.072642,0.0,459.4534,462.8561,464.3027,739.7415
sensor_17,220274.0,NaN,NaN,NaN,421.127517,129.156175,0.0,454.138825,462.02025,466.857075,599.999939
sensor_18,220274.0,NaN,NaN,NaN,2.303785,0.765883,0.0,2.447542,2.533704,2.587682,4.87325
sensor_19,220304.0,NaN,NaN,NaN,590.829775,199.34582,0.0,662.768975,665.6724,667.1467,878.9179
sensor_20,220304.0,NaN,NaN,NaN,360.805165,101.974118,0.0,398.0215,399.367,400.0884,448.9079
sensor_21,220304.0,NaN,NaN,NaN,796.225942,226.679317,95.52766,875.4644,879.6976,882.1299,1107.526
sensor_22,220279.0,NaN,NaN,NaN,459.792815,154.528337,0.0,478.9626,531.8559,534.25485,594.0611
sensor_23,220304.0,NaN,NaN,NaN,922.609264,291.83528,0.0,950.9224,981.925,1090.808,1227.564
sensor_24,220304.0,NaN,NaN,NaN,556.235397,182.297979,0.0,601.15105,625.8735,628.607725,1000.0
sensor_25,220284.0,NaN,NaN,NaN,649.144799,220.865166,0.0,693.9578,740.2035,750.357125,839.575
sensor_26,220300.0,NaN,NaN,NaN,786.411781,246.663608,43.15479,790.489575,861.8696,919.104775,1214.42
sensor_27,220304.0,NaN,NaN,NaN,501.506589,169.823173,0.0,448.29795,494.46845,536.27455,2000.0
sensor_28,220304.0,NaN,NaN,NaN,851.690339,313.074032,4.319347,782.682625,967.27985,1043.9765,1841.146
sensor_29,220248.0,NaN,NaN,NaN,576.195305,225.764091,0.636574,518.947225,564.8725,744.021475,1466.281
sensor_30,220059.0,NaN,NaN,NaN,614.596442,195.726872,0.0,627.7778,668.9814,697.2222,1600.0
sensor_31,220304.0,NaN,NaN,NaN,863.3231,283.54476,23.95833,839.0624,917.7083,981.2499,1800.0
sensor_32,220252.0,NaN,NaN,NaN,804.283915,260.602361,0.240716,760.607475,878.85075,943.877625,1839.211
sensor_33,220304.0,NaN,NaN,NaN,486.40598,150.751836,6.460602,489.761075,512.27175,555.163225,1578.6
sensor_34,220304.0,NaN,NaN,NaN,234.971776,88.376065,54.88237,172.4863,226.35605,316.84495,425.5498
sensor_35,220304.0,NaN,NaN,NaN,427.129817,141.772519,0.0,353.176625,473.34935,528.891025,694.479126
sensor_36,220304.0,NaN,NaN,NaN,593.033876,289.385511,2.26097,288.547575,709.66805,837.333025,984.0607
sensor_37,220304.0,NaN,NaN,NaN,60.78736,37.604883,0.0,28.79922,64.295485,90.821928,174.9012
sensor_38,220293.0,NaN,NaN,NaN,49.655946,10.540397,24.479166,45.57291,49.47916,53.64583,417.7083
sensor_39,220293.0,NaN,NaN,NaN,36.610444,15.613723,19.27083,32.55208,35.41666,39.0625,547.9166
sensor_40,220293.0,NaN,NaN,NaN,68.84453,21.371139,23.4375,57.8125,66.40625,77.86458,512.7604
sensor_41,220293.0,NaN,NaN,NaN,35.365126,7.898665,20.83333,32.55208,34.895832,37.76041,420.3125
sensor_42,220293.0,NaN,NaN,NaN,35.453455,10.259521,22.135416,32.8125,35.15625,36.979164,374.2188
sensor_43,220293.0,NaN,NaN,NaN,43.879591,11.044404,24.479166,39.58333,42.96875,46.61458,408.5937
sensor_44,220293.0,NaN,NaN,NaN,42.656877,11.576355,25.752316,36.747684,40.50926,45.13889,1000.0
sensor_45,220293.0,NaN,NaN,NaN,43.094984,12.83752,26.331018,36.747684,40.21991,44.84954,320.3125
sensor_46,220293.0,NaN,NaN,NaN,48.018585,15.641284,26.331018,40.509258,44.84954,51.21528,370.3704
sensor_47,220293.0,NaN,NaN,NaN,44.340903,10.442437,27.19907,39.0625,42.53472,46.58565,303.5301
sensor_48,220293.0,NaN,NaN,NaN,150.889044,82.244957,26.331018,83.91203,138.0208,208.3333,561.632
sensor_49,220293.0,NaN,NaN,NaN,57.119968,19.143598,26.62037,47.74306,52.66204,60.76389,464.4097
sensor_50,143303.0,NaN,NaN,NaN,183.04926,65.25865,27.488426,167.5347,193.8657,219.9074,1000.0
sensor_51,204937.0,NaN,NaN,NaN,202.699667,109.588607,27.777779,179.1088,197.338,216.7245,1000.0
machine_status,220320,3,NORMAL,205836,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [10]:
df_old.isnull().sum()

Unnamed: 0             0
timestamp              0
sensor_00          10208
sensor_01            369
sensor_02             19
sensor_03             19
sensor_04             19
sensor_05             19
sensor_06           4798
sensor_07           5451
sensor_08           5107
sensor_09           4595
sensor_10             19
sensor_11             19
sensor_12             19
sensor_13             19
sensor_14             21
sensor_15         220320
sensor_16             31
sensor_17             46
sensor_18             46
sensor_19             16
sensor_20             16
sensor_21             16
sensor_22             41
sensor_23             16
sensor_24             16
sensor_25             36
sensor_26             20
sensor_27             16
sensor_28             16
sensor_29             72
sensor_30            261
sensor_31             16
sensor_32             68
sensor_33             16
sensor_34             16
sensor_35             16
sensor_36             16
sensor_37             16
sensor_38             27
sensor_39             27
sensor_40             27
sensor_41             27
sensor_42             27
sensor_43             27
sensor_44             27
sensor_45             27
sensor_46             27
sensor_47             27
sensor_48             27
sensor_49             27
sensor_50          77017
sensor_51          15383
machine_status         0
dtype: int64

In [12]:
df_old.duplicated().sum()

np.int64(0)

In [13]:
df_old["machine_status"].value_counts()

machine_status
NORMAL        205836
RECOVERING     14477
BROKEN             7
Name: count, dtype: int64

In [14]:
df_old["machine_status"].value_counts()

machine_status
NORMAL        205836
RECOVERING     14477
BROKEN             7
Name: count, dtype: int64

In [15]:
df_old["timestamp"] = pd.to_datetime(
    df_old["timestamp"],
    errors="coerce"
)

In [16]:
print(df_old["timestamp"].min())
print(df_old["timestamp"].max())

2018-04-01 00:00:00
2018-08-31 23:59:00

In [17]:
df_old = df_old.sort_values("timestamp").reset_index(drop=True)

In [18]:
sensor_columns = [
    col for col in df_old.columns
    if col.startswith("sensor_")
]

sensor_profile = pd.DataFrame({
    "missing_count": df_old[sensor_columns].isnull().sum(),
    "missing_percentage": df_old[sensor_columns].isnull().mean() * 100,
    "unique_values": df_old[sensor_columns].nunique(),
    "mean": df_old[sensor_columns].mean(),
    "std": df_old[sensor_columns].std(),
    "min": df_old[sensor_columns].min(),
    "max": df_old[sensor_columns].max()
})

sensor_profile.sort_values(
    "missing_percentage",
    ascending=False
)

,missing_count,missing_percentage,unique_values,mean,std,min,max
sensor_15,220320,100.000000,0,NaN,NaN,NaN,NaN
sensor_50,77017,34.956881,1135,183.049260,65.258650,27.488426,1000.000000
sensor_51,15383,6.982117,1108,202.699667,109.588607,27.777779,1000.000000
sensor_00,10208,4.633261,1253,2.372221,0.412227,0.000000,2.549016
sensor_07,5451,2.474129,531,15.843152,2.201155,0.000000,23.596640
sensor_08,5107,2.317992,626,15.200721,2.037390,0.028935,24.348960
sensor_06,4798,2.177741,812,13.501537,2.163736,0.014468,22.251160
sensor_09,4595,2.085603,565,14.799210,2.091963,0.000000,25.000000
sensor_01,369,0.167484,831,47.591611,3.296666,0.000000,56.727430
sensor_30,261,0.118464,2070,614.596442,195.726872,0.000000,1600.000000
sensor_29,72,0.032680,201908,576.195305,225.764091,0.636574,1466.281000
sensor_32,68,0.030864,205414,804.283915,260.602361,0.240716,1839.211000
sensor_18,46,0.020879,152603,2.303785,0.765883,0.000000,4.873250
sensor_17,46,0.020879,148000,421.127517,129.156175,0.000000,599.999939
sensor_22,41,0.018609,126401,459.792815,154.528337,0.000000,594.061100
sensor_25,36,0.016340,165999,649.144799,220.865166,0.000000,839.575000
sensor_16,31,0.014070,110522,416.472892,126.072642,0.000000,739.741500
sensor_44,27,0.012255,628,42.656877,11.576355,25.752316,1000.000000
sensor_41,27,0.012255,594,35.365126,7.898665,20.833330,420.312500
sensor_40,27,0.012255,878,68.844530,21.371139,23.437500,512.760400
sensor_49,27,0.012255,827,57.119968,19.143598,26.620370,464.409700
sensor_48,27,0.012255,1440,150.889044,82.244957,26.331018,561.632000
sensor_45,27,0.012255,675,43.094984,12.837520,26.331018,320.312500
sensor_42,27,0.012255,699,35.453455,10.259521,22.135416,374.218800
sensor_38,27,0.012255,602,49.655946,10.540397,24.479166,417.708300
sensor_39,27,0.012255,909,36.610444,15.613723,19.270830,547.916600
sensor_46,27,0.012255,845,48.018585,15.641284,26.331018,370.370400
sensor_47,27,0.012255,621,44.340903,10.442437,27.199070,303.530100
sensor_43,27,0.012255,713,43.879591,11.044404,24.479166,408.593700
sensor_14,21,0.009532,94564,376.860041,113.206382,32.409550,500.000000
sensor_26,20,0.009078,179718,786.411781,246.663608,43.154790,1214.420000
sensor_02,19,0.008624,831,50.867392,3.666820,33.159720,56.032990
sensor_04,19,0.008624,7844,590.673936,144.023912,2.798032,800.000000
sensor_05,19,0.008624,190751,73.396414,17.298247,0.000000,99.999880
sensor_10,19,0.008624,198804,41.470339,12.093519,0.000000,76.106860
sensor_03,19,0.008624,588,43.752481,2.418887,31.640620,48.220490
sensor_13,19,0.008624,191983,7.078858,6.901755,0.000000,31.187550
sensor_12,19,0.008624,187145,29.136975,10.113935,0.000000,45.000000
sensor_11,19,0.008624,196368,41.918319,13.056425,0.000000,60.000000
sensor_19,16,0.007262,100422,590.829775,199.345820,0.000000,878.917900
sensor_35,16,0.007262,201781,427.129817,141.772519,0.000000,694.479126
sensor_34,16,0.007262,203895,234.971776,88.376065,54.882370,425.549800
sensor_24,16,0.007262,133778,556.235397,182.297979,0.000000,1000.000000
sensor_27,16,0.007262,203198,501.506589,169.823173,0.000000,2000.000000
sensor_20,16,0.007262,92129,360.805165,101.974118,0.000000,448.907900
sensor_23,16,0.007262,119286,922.609264,291.835280,0.000000,1227.564000
sensor_33,16,0.007262,200855,486.405980,150.751836,6.460602,1578.600000
sensor_31,16,0.007262,2685,863.323100,283.544760,23.958330,1800.000000
sensor_28,16,0.007262,189278,851.690339,313.074032,4.319347,1841.146000
sensor_21,16,0.007262,131083,796.225942,226.679317,95.527660,1107.526000
sensor_37,16,0.007262,188898,60.787360,37.604883,0.000000,174.901200
sensor_36,16,0.007262,201437,593.033876,289.385511,2.260970,984.060700